#!/usr/bin/env python3
import json

with open("data/reuses.json", "r", encoding="utf-8") as f:
    reuses = json.load(f)

existing_ids = set(r["id"] for r in reuses)

additional_apps = [
    {
        "id": "el-coco",
        "name": "El Coco",
        "tagline": "Nutrition & ultra-processing barcode scanner in Spain",
        "description": "One of the most popular nutrition apps in Spain with over 500,000 installs. Scans food products to evaluate nutritional quality (Nutri-Score) and ultra-processing level (NOVA), with a dedicated contributor account on Open Food Facts.",
        "theme": "nutrition",
        "project": "openfoodfacts",
        "country": "esp",
        "country_label": "Spain",
        "domain": "elcoco.es",
        "website": "https://elcoco.es/",
        "play_store": "https://play.google.com/store/apps/details?id=es.elcoco.app",
        "app_store": "https://apps.apple.com/es/app/el-coco-come-m%C3%A1s-sano/id1446005742",
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": False,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": True,
        "keywords": "el coco spain espana nutriscore nova ultra-procesados scanner nutricion"
    },
    {
        "id": "pantrist",
        "name": "Pantrist",
        "tagline": "Smart shopping list & home pantry expiration manager",
        "description": "Household inventory and shopping list application with over 20,000 installs across Europe. Directly retrieves product names, brands, categories, and front photos from Open Food Facts to organize pantries and prevent food waste.",
        "theme": "tools",
        "project": "openfoodfacts",
        "country": "deu",
        "country_label": "Germany & Europe",
        "domain": "pantrist.com",
        "website": "https://pantrist.com",
        "play_store": "https://play.google.com/store/apps/details?id=com.nicolueg.pantrist",
        "app_store": "https://apps.apple.com/us/app/pantrist-shopping-pantry/id1531156635",
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": True,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": True,
        "keywords": "pantrist inventory pantry shopping list expiration vorrat einkaufsliste"
    },
    {
        "id": "buyornot",
        "name": "BuyOrNot",
        "tagline": "Societal, ethical & health product scanner by I-Boycott",
        "description": "Developed by citizen movement I-Boycott with 100,000+ installs. Scans groceries to show health evaluations alongside corporate campaigns, ethical scandals, and environmental impact. Fully compliant with the ODbL license.",
        "theme": "environment",
        "project": "openfoodfacts",
        "country": "fra",
        "country_label": "France",
        "domain": "i-boycott.org",
        "website": "https://www.i-boycott.org/",
        "play_store": "https://play.google.com/store/apps/details?id=org.buyornot.scan",
        "app_store": None,
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": True,
        "odbl_compliant": True,
        "open_source": True,
        "license": "Open Source",
        "featured": True,
        "keywords": "buyornot i-boycott ethique consommation citoyenne boycott scandales rse"
    },
    {
        "id": "mylabel",
        "name": "MyLabel",
        "tagline": "Personalized ethical, environmental & health consumer guide",
        "description": "Deciphers supermarket items according to 24 societal criteria (carbon footprint, biodiversity, fair pay, animal welfare, and Nutri-Score) in partnership with independent NGOs. An active contributor to Open Food Facts via its contributor account.",
        "theme": "environment",
        "project": "openfoodfacts",
        "country": "fra",
        "country_label": "France",
        "domain": "mylabel.io",
        "website": "https://www.mylabel.io/",
        "play_store": "https://play.google.com/store/apps/details?id=io.mylabel.main",
        "app_store": "https://itunes.apple.com/fr/app/mylabel-my-values-my-choice/id1316896135",
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": False,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": True,
        "keywords": "mylabel rse ethique environnement nutriscore conso responsable climat"
    },
    {
        "id": "quelproduit",
        "name": "QuelProduit",
        "tagline": "Consumer safety & independent ratings by UFC-Que Choisir",
        "description": "The official consumer scanning app by leading French consumer association UFC-Que Choisir with over 500,000 installs. Analyzes food nutrition, cosmetic ingredients, and household chemical risks.",
        "theme": "nutrition",
        "project": "openfoodfacts",
        "country": "fra",
        "country_label": "France",
        "domain": "quechoisir.org",
        "website": "https://www.quechoisir.org/application-mobile-quelproduit-n88420/",
        "play_store": "https://play.google.com/store/apps/details?id=com.quechoisir.quelproduit",
        "app_store": "https://apps.apple.com/fr/app/quelproduit/id1509421160",
        "fdroid": None,
        "github": None,
        "contributes_data": False,
        "contributes_photos": False,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": True,
        "keywords": "quelproduit ufc que choisir consommateur sante securite risques nutriscore"
    },
    {
        "id": "grocy-android",
        "name": "Grocy Android",
        "tagline": "Open-source mobile companion for Grocy ERP for your kitchen",
        "description": "A community open-source Android client for Grocy, the self-hosted ERP and pantry management platform for homes. Integrates barcode scanning directly against the Open Food Facts API to streamline inventory stocking.",
        "theme": "tools",
        "project": "openfoodfacts",
        "country": "global",
        "country_label": "Worldwide",
        "domain": "github.com",
        "website": "https://github.com/patzly/grocy-android",
        "play_store": "https://play.google.com/store/apps/details?id=xyz.zedler.patrick.grocy",
        "app_store": None,
        "fdroid": "https://f-droid.org/packages/xyz.zedler.patrick.grocy/",
        "github": "https://github.com/patzly/grocy-android",
        "contributes_data": False,
        "contributes_photos": False,
        "odbl_compliant": True,
        "open_source": True,
        "license": "GPLv3",
        "featured": True,
        "keywords": "grocy self-hosted home assistant erp kitchen pantry inventory open source"
    },
    {
        "id": "truthin",
        "name": "TruthIn",
        "tagline": "Nutrition & cosmetic ingredient transparency in India",
        "description": "Helps Indian consumers decipher food packages and cosmetic ingredient safety. Built with Flutter, queries Open Food Facts for packaged goods, and onboarded Indian food products onto the open database.",
        "theme": "nutrition",
        "project": "openfoodfacts",
        "country": "ind",
        "country_label": "India",
        "domain": "truthin.in",
        "website": "https://truthin.in",
        "play_store": "https://play.google.com/store/apps/details?id=com.natfirst.truthin",
        "app_store": "https://apps.apple.com/in/app/truthin/id6450003063",
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": False,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": False,
        "keywords": "truthin india cosmetics food ingredients additives safety scanner"
    },
    {
        "id": "intolerapp",
        "name": "InTolerApp",
        "tagline": "FODMAP, histamine, lactose & fructose food intolerance scanner",
        "description": "Designed for individuals suffering from IBS and food intolerances. Scans ingredients to flag high-FODMAP components, histamine triggers, gluten, and lactose across North America and Europe.",
        "theme": "allergies",
        "project": "openfoodfacts",
        "country": "deu",
        "country_label": "Germany, US & Europe",
        "domain": "intolerapp.de",
        "website": "https://intolerapp.de",
        "play_store": "https://play.google.com/store/apps/details?id=de.jonahhadt.intoler",
        "app_store": "https://apps.apple.com/us/app/fodmap-app-intolerapp/id6446506660",
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": True,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": False,
        "keywords": "intolerapp fodmap ibs histamine fructose lactose intolerances allergies"
    },
    {
        "id": "fodmap-facile",
        "name": "Fodmap Facile",
        "tagline": "Personalized FODMAP scanner for irritable bowel syndrome (IBS)",
        "description": "Helps French-speaking individuals manage IBS by scanning grocery barcodes for oligosaccharides, disaccharides, and polyols. The team verifies product photos and submits corrections back to Open Food Facts.",
        "theme": "allergies",
        "project": "openfoodfacts",
        "country": "fra",
        "country_label": "France & Belgium",
        "domain": "fodmapfacile.net",
        "website": "https://fodmapfacile.net",
        "play_store": "https://play.google.com/store/apps/details?id=com.lunisoft.fodmapfacile",
        "app_store": "https://apps.apple.com/fr/app/fodmap-facile-scan-produits/id6743708203",
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": True,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": False,
        "keywords": "fodmap facile intestin irritable colon irritable sii digestion scanner"
    },
    {
        "id": "bite-insight",
        "name": "Bite Insight",
        "tagline": "Impact insight cards for health conditions & allergens",
        "description": "Launched in the UK, US, France, Germany, Spain, Italy, Australia, and India. Uses Open Food Facts ingredient lists and nutritional tables to generate tailored impact cards for users with dietary preferences and medical health conditions.",
        "theme": "allergies",
        "project": "openfoodfacts",
        "country": "gbr",
        "country_label": "UK, US & Europe",
        "domain": "biteinsight.app",
        "website": "https://biteinsight.app",
        "play_store": "https://play.google.com/store/apps/details?id=com.biteinsightapp.gcahill",
        "app_store": "https://apps.apple.com/gb/app/bite-insight-food-scanner/id6760033160",
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": True,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": False,
        "keywords": "bite insight allergy health conditions impact nutrition scan scanner"
    },
    {
        "id": "cedulka",
        "name": "Cedulka",
        "tagline": "Celiac safety & allergen food scanner in the Czech Republic",
        "description": "Built using Kotlin Multiplatform for Android, iOS, and Desktop. Specifically created to address the coverage gap for gluten and allergen data in the Czech Republic and Central Europe, actively contributing back verified packaging photos.",
        "theme": "allergies",
        "project": "openfoodfacts",
        "country": "cze",
        "country_label": "Czech Republic & EU",
        "domain": "cedulka.app",
        "website": "https://cedulka.app",
        "play_store": "https://play.google.com/store/apps/details?id=cz.vanamas.cedulka",
        "app_store": None,
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": True,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": False,
        "keywords": "cedulka czech celiac bezlepku gluten allergy allergens potraviny"
    },
    {
        "id": "pola",
        "name": "Pola",
        "tagline": "Polish corporate ownership & local manufacturing scanner",
        "description": "Over 500,000 installs in Poland. Pola helps consumers support local businesses and economic transparency by scanning barcodes to compute a Polishness and provenance score (0-100) based on manufacturing, HQ, and capital ownership.",
        "theme": "traceability",
        "project": "openfoodfacts",
        "country": "pol",
        "country_label": "Poland",
        "domain": "pola-app.pl",
        "website": "https://www.pola-app.pl/",
        "play_store": "https://play.google.com/store/apps/details?id=pl.pola_app",
        "app_store": None,
        "fdroid": None,
        "github": None,
        "contributes_data": False,
        "contributes_photos": False,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Non-profit",
        "featured": True,
        "keywords": "pola poland polska local origin provenance polish manufacturing trace"
    },
    {
        "id": "toxfox",
        "name": "ToxFox",
        "tagline": "Detect pollutants, microplastics & endocrine disruptors in cosmetics",
        "description": "The flagship consumer protection app created by BUND (Friends of the Earth Germany) with over 1 million installs. Scans cosmetic and everyday items to warn consumers about harmful chemicals and endocrine disruptors.",
        "theme": "tools",
        "project": "openbeautyfacts",
        "country": "deu",
        "country_label": "Germany",
        "domain": "bund.net",
        "website": "https://www.bund.net/themen/chemie/toxfox/",
        "play_store": "https://play.google.com/store/apps/details?id=de.bund.toxfox",
        "app_store": None,
        "fdroid": None,
        "github": None,
        "contributes_data": False,
        "contributes_photos": False,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Non-profit NGO",
        "featured": True,
        "keywords": "toxfox bund germany cosmetics open beauty facts chemie schadstoffe mikroplastik"
    },
    {
        "id": "seed-oil-scout",
        "name": "Seed Oil Scout",
        "tagline": "Find seed-oil-free restaurants & scan grocery ingredients",
        "description": "A global community platform built with Flutter that maps seed-oil-free restaurants and analyzes supermarket food items for industrial seed oils (canola, corn, cotton, soy, sunflower). Contributes product labels back to Open Food Facts.",
        "theme": "nutrition",
        "project": "openfoodfacts",
        "country": "usa",
        "country_label": "United States & Global",
        "domain": "seedoilscout.com",
        "website": "https://seedoilscout.com",
        "play_store": "https://play.google.com/store/apps/details?id=com.seedoilscout.app",
        "app_store": "https://apps.apple.com/us/app/seed-oil-scout/id1630713437",
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": True,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": False,
        "keywords": "seed oil scout oils olive oil butter tallow canola inflammation"
    },
    {
        "id": "lattosio-free",
        "name": "Lattosio Free",
        "tagline": "Italian scanner for lactose intolerance and milk derivatives",
        "description": "Helps consumers in Italy with lactose intolerance verify food ingredients and identify hidden dairy derivatives. Uses the Open Food Facts API to parse complex Italian food labels.",
        "theme": "allergies",
        "project": "openfoodfacts",
        "country": "ita",
        "country_label": "Italy",
        "domain": "arcadone.it",
        "website": "https://arcadone.it",
        "play_store": "https://play.google.com/store/apps/details?id=com.arcadone.sosmilk",
        "app_store": "https://apps.apple.com/it/app/lattosio-free/id6743235131",
        "fdroid": None,
        "github": None,
        "contributes_data": False,
        "contributes_photos": False,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": False,
        "keywords": "lattosio free senza lattosio lactose italy italia latte intolleranza"
    },
    {
        "id": "ya-quoi-dedans",
        "name": "Y'A Quoi Dedans",
        "tagline": "Product ingredients & additives decipherer by Coopérative U",
        "description": "Retailer mobile application with over 100,000 installs in France by Coopérative U (Système U). Helps shoppers understand product compositions and additive risks by utilizing Open Food Facts open data.",
        "theme": "nutrition",
        "project": "openfoodfacts",
        "country": "fra",
        "country_label": "France",
        "domain": "magasins-u.com",
        "website": "https://www.magasins-u.com/cooperative-u/app-y-a-quoi-dedans",
        "play_store": "https://play.google.com/store/apps/details?id=com.su.yaqd",
        "app_store": "https://apps.apple.com/fr/app/ya-quoi-dedans/id1391001466",
        "fdroid": None,
        "github": None,
        "contributes_data": True,
        "contributes_photos": True,
        "odbl_compliant": True,
        "open_source": False,
        "license": "Proprietary",
        "featured": False,
        "keywords": "ya quoi dedans systeme u magasins u distributeur additifs nutriscore"
    }
]

for app in additional_apps:
    if app["id"] not in existing_ids:
        reuses.append(app)
        existing_ids.add(app["id"])

with open("data/reuses.json", "w", encoding="utf-8") as f:
    json.dump(reuses, f, ensure_ascii=False, indent=2)

print(f"Total reuses now in data/reuses.json: {len(reuses)}")
